name: file-existence
on:
  push:
jobs:
  file-existence:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check file existence
        uses: andstor/file-existence-action@v1
        with:
          files: "testtest.js"
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [ file-existence ]
    if: always() && (needs.file_existence.result == 'failure')
    steps:
      # email sender
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build job of ${{github.repository}} failed!
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} failed!
          to: julia.taro@gmail.com
          from: Github actions